/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gps_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double latitude;
    public String latitude_s;
    public double longitude;
    public String longitude_s;
    public double altitude;
    public String altitude_s;
    public double easting;
    public double northing;
    public short zone;
    public String zoneLetter;
 
    public gps_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xca8fd0c44347053fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.gps_t.class))
            return 0L;
 
        classes.add(exlcm.gps_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.latitude); 
 
        __strbuf = new char[this.latitude_s.length()]; this.latitude_s.getChars(0, this.latitude_s.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeDouble(this.longitude); 
 
        __strbuf = new char[this.longitude_s.length()]; this.longitude_s.getChars(0, this.longitude_s.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeDouble(this.altitude); 
 
        __strbuf = new char[this.altitude_s.length()]; this.altitude_s.getChars(0, this.altitude_s.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeDouble(this.easting); 
 
        outs.writeDouble(this.northing); 
 
        outs.writeShort(this.zone); 
 
        __strbuf = new char[this.zoneLetter.length()]; this.zoneLetter.getChars(0, this.zoneLetter.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public gps_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gps_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.gps_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.gps_t o = new exlcm.gps_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = ins.readLong();
 
        this.latitude = ins.readDouble();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.latitude_s = new String(__strbuf);
 
        this.longitude = ins.readDouble();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.longitude_s = new String(__strbuf);
 
        this.altitude = ins.readDouble();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.altitude_s = new String(__strbuf);
 
        this.easting = ins.readDouble();
 
        this.northing = ins.readDouble();
 
        this.zone = ins.readShort();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.zoneLetter = new String(__strbuf);
 
    }
 
    public exlcm.gps_t copy()
    {
        exlcm.gps_t outobj = new exlcm.gps_t();
        outobj.timestamp = this.timestamp;
 
        outobj.latitude = this.latitude;
 
        outobj.latitude_s = this.latitude_s;
 
        outobj.longitude = this.longitude;
 
        outobj.longitude_s = this.longitude_s;
 
        outobj.altitude = this.altitude;
 
        outobj.altitude_s = this.altitude_s;
 
        outobj.easting = this.easting;
 
        outobj.northing = this.northing;
 
        outobj.zone = this.zone;
 
        outobj.zoneLetter = this.zoneLetter;
 
        return outobj;
    }
 
}

