/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imu_t implements lcm.lcm.LCMEncodable
{
    public double magX;
    public double magY;
    public double magZ;
    public double accelX;
    public double accelY;
    public double accelZ;
    public double gyroX;
    public double gyroY;
    public double gyroZ;
    public double temp;
    public double pressure;
 
    public imu_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x69e9d1c34d974ff2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.imu_t.class))
            return 0L;
 
        classes.add(exlcm.imu_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.magX); 
 
        outs.writeDouble(this.magY); 
 
        outs.writeDouble(this.magZ); 
 
        outs.writeDouble(this.accelX); 
 
        outs.writeDouble(this.accelY); 
 
        outs.writeDouble(this.accelZ); 
 
        outs.writeDouble(this.gyroX); 
 
        outs.writeDouble(this.gyroY); 
 
        outs.writeDouble(this.gyroZ); 
 
        outs.writeDouble(this.temp); 
 
        outs.writeDouble(this.pressure); 
 
    }
 
    public imu_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imu_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.imu_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.imu_t o = new exlcm.imu_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.magX = ins.readDouble();
 
        this.magY = ins.readDouble();
 
        this.magZ = ins.readDouble();
 
        this.accelX = ins.readDouble();
 
        this.accelY = ins.readDouble();
 
        this.accelZ = ins.readDouble();
 
        this.gyroX = ins.readDouble();
 
        this.gyroY = ins.readDouble();
 
        this.gyroZ = ins.readDouble();
 
        this.temp = ins.readDouble();
 
        this.pressure = ins.readDouble();
 
    }
 
    public exlcm.imu_t copy()
    {
        exlcm.imu_t outobj = new exlcm.imu_t();
        outobj.magX = this.magX;
 
        outobj.magY = this.magY;
 
        outobj.magZ = this.magZ;
 
        outobj.accelX = this.accelX;
 
        outobj.accelY = this.accelY;
 
        outobj.accelZ = this.accelZ;
 
        outobj.gyroX = this.gyroX;
 
        outobj.gyroY = this.gyroY;
 
        outobj.gyroZ = this.gyroZ;
 
        outobj.temp = this.temp;
 
        outobj.pressure = this.pressure;
 
        return outobj;
    }
 
}

